name: build x64 release

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1
      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release /p:Platform=x64 CS2_External.sln
      - name: Rename EXE to AimStar-dev-${{github.sha}}.exe
        run: |
          del AimStar-*.exe
          ren AimStar.exe AimStar-${{github.sha}}.exe
        working-directory: .\x64\Release\
      - name: Upload the output
        uses: actions/upload-artifact@v2
        with:
          name: ci
          path: .\x64\Release\*
  create_release:
    runs-on: ubuntu-latest
    needs: build
    name: Create Release
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ci
      - name: Run latest-tag
        uses: EndBug/latest-tag@84c87607fcb948bcef069c9a27445e653113979f
        with:
          ref: autobuild
      - name: automatic Release ci
        uses: softprops/action-gh-release@v1
        with:
          name: autobuild [${{github.sha}}]
          tag_name: autobuild
          body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Full Commit Hash of Latest autobuild:
            ```
            ${{github.sha}}
            ```
            No support for any autobuild version except the latest autobuild
          files: |
            AimStar-${{github.sha}}.exe
          prerelease: true
