name: build x64 release ci

on: 
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@main
      - name: Build with MSBuild
        run: msbuild CS2_External\CS2_External.vcxproj /p:Configuration=Ring3 /p:Platform=x64
      - name: Rename EXE to AimStar-Ring3-${{github.sha}}.exe
        run: |
          del AimStar-Ring3-*.exe
          ren AimStar-Ring3.exe AimStar-Ring3-${{github.sha}}.exe
        working-directory: CS2_External\x64\Ring3\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: ci
          path: CS2_External\x64\Ring3\*
  buildKernel:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@main
      - name: Build with MSBuild
        run: msbuild CS2_External.sln /p:Configuration=Ring0 /p:Platform=x64
      - name: Rename EXE to AimStar-Ring0-${{github.sha}}.exe
        run: |
          del AimStar-Ring0-*.exe
          ren AimStar-Ring0.exe AimStar-Ring0-${{github.sha}}.exe
        working-directory: x64\Ring0\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: cir0
          path: x64\Ring0\*
      - name: Upload the kernel
        uses: actions/upload-artifact@main
        with:
          name: cike
          path: x64\Release\*
  buildllvm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compile with llvm
        run: msbuild CS2_External\CS2_External.vcxproj /p:Configuration=Ring3 /p:Platform="x64" /p:CLToolExe=clang-cl.exe /p:CLToolPath="C:\Program Files\LLVM\bin"
      - name: Rename EXE to LLVM-AimStar-Ring3-${{github.sha}}.exe
        run: |
          del LLVM-AimStar-Ring3-*.exe
          ren AimStar-Ring3.exe LLVM-AimStar-Ring3-${{github.sha}}.exe
        working-directory: CS2_External\x64\Ring3\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: llvm
          path: CS2_External\x64\Ring3\*
  create_release:
    runs-on: ubuntu-latest
    needs: [build, buildKernel, buildllvm]
    name: Create Release
    steps:
      - uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main
      - run: ls -R
      - name: Zip ci
        uses: vimtor/action-zip@master
        with:
          files: ./ci/AimStar-Ring3-${{github.sha}}.exe           
          dest: AimStar-R3-Autobuild.zip
      - name: Zip cir0
        uses: vimtor/action-zip@master
        with:
          files: ./cir0/AimStar-Ring0-${{github.sha}}.exe
          dest: AimStar-R0-Autobuild.zip
      - name: Zip cike
        uses: vimtor/action-zip@master
        with:
          files: ./cike/Driver.sys
          dest: AimStar-Driver-Autobuild.zip    
      - name: Zip llvm ci
        uses: vimtor/action-zip@master
        with:
          files: ./llvm/LLVM-AimStar-Ring3-${{github.sha}}.exe         
          dest: AimStar-LLVM-Autobuild.zip
      - name: Delete tag
        run: gh release delete autobuild --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run latest-tag
        uses: EndBug/latest-tag@main
        with:
          ref: autobuild
      - name: automatic Release ci
        uses: softprops/action-gh-release@master
        with:
          name: autobuild [${{github.sha}}]
          tag_name: autobuild
          body: |
            **This release has been built by Github Actions, and may contains some issues**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Full Commit Hash of Latest autobuild:
            ```
            ${{github.sha}}
            ```
            No support for any autobuild version except the latest autobuild
          #  Try llvm build if msvc build doesn't works right
          files: |
            AimStar-R0-Autobuild.zip
            AimStar-Driver-Autobuild.zip
            AimStar-R3-Autobuild.zip
            AimStar-LLVM-Autobuild.zip
          prerelease: true
        
