name: buildcheck x64 release llvm

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  buildllvm:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      name: C++ CI with Visual Studio LLVM
    - name: Set up Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
    - name: Compile with MSBuild
      run: msbuild CS2_External\CS2_External.vcxproj /p:Configuration=Ring3 /p:Platform="x64" /p:CLToolExe=clang-cl.exe /p:CLToolPath="C:\Program Files\LLVM\bin"
